### ISSUE TITLE
Formtastic compatibility

### ISSUE THREAD

**Issue by Nerian** [thetron/css3buttons_rails_helpers#25]
Hi,

I am using css3buttons_rails_helpers with formtastic and I am having some issues. The submit button doesn't look right.

I'm using Rails 3.1

application.css

``` css
/*
 * This is a manifest file that'll automatically include all the stylesheets available in this directory
 * and any sub-directories. You're free to add application-wide styles to this file and they'll appear at
 * the top of the compiled file, but it's generally better to create a new file per style scope.
 *= require_self
 *= require_tree . 
 *= require formtastic
 *= require my_formtastic_changes
 *= require css3buttons/without-reset
*/
```

my_formtastic_changes.css

``` css
form.formtastic input.button, form.formtastic.button.button {
  height: 25px;
  padding: 0.2em 1em 0.2em 2.5em;
  font-family: sans-serif;
  font-size: 11px;
  margin-left: 5px;
}
```

The problematic code:

``` haml
= semantic_form_for @mentor do |f|
  = f.input :name
  = f.commit_button 'Save new mentor'
```

This is what I see:

http://dl.dropbox.com/u/834494/screenshot.png

**Comment by Nerian** [comment]
This css code fixes the issue. I can make a pull request if you want.

``` css
form.formtastic input.button {
  height: 25px;
  padding: 0.2em 1em 0.2em 1em;
  font-family: sans-serif;
  font-size: 11px;
  margin-left: 0px;
}

form.formtastic li.commit.button{
    margin: 0;
    padding: 0;     
    border: 0;
    border-radius: 0;
}
```
